### ISSUE TITLE
Feature: goal system

### ISSUE THREAD

**Issue by auscyber** [AusCyberman/dotfile-sync#6]
## Add a sort of goal system
Goals can be declared like
`.links.toml`
```toml
[goals.rice]
enabled = true

[goals.full-system-nixos]
requires = "rice"

[[links]]
name = "fetch"
goal = "rice"
```
an imperfect system but the idea that i have so far

- [ ] Added goals
- [ ]
